; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#include "CodeDependencies.iss"

#define MyAppName "DSHDesktop"
#define MyAppVersion "v1.0.0"
#define MyAppPublisher "szWrn@Github"
#define MyAppURL "https://github.com/szWrn/DSHDesktop"
#define MyAppExeName "dsh-desktop.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{66963645-E753-4D13-9367-305B4EAA43F9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=D:\Projects\DSHDesktop\LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=D:\Projects\DSHDesktop\src-tauri\target\release\installer
OutputBaseFilename=dsh-desktop_1.0.0_win_x64
SetupIconFile=D:\Projects\DSHDesktop\src-tauri\icons\icon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Projects\DSHDesktop\src-tauri\target\release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
// 安装时检测并安装 Node.js（DSH 服务通过 npx 启动，运行时依赖 Node.js）
function Dependency_IsNodeInstalled: Boolean;
begin
  // Node.js 官方 MSI 安装器会在注册表写入 SOFTWARE\Node.js 键
  Result := RegKeyExists(Dependency_ArchHKLM, 'SOFTWARE\Node.js')
         or RegKeyExists(HKCU, 'SOFTWARE\Node.js');
end;

procedure Dependency_AddNode;
begin
  // https://nodejs.org/dist/
  // 如需校验下载完整性，请从 https://nodejs.org/dist/v24.19.0/SHASUMS256.txt
  // 获取对应 .msi 的 SHA-256 值，填入最后一个参数（当前留空表示跳过校验）。
  Dependency_AddIfMissing(not Dependency_IsNodeInstalled,
    'node' + Dependency_ArchSuffix + '.msi',
    Dependency_PassiveOrQuiet('/passive', '/quiet') + ' /norestart',
    'Node.js v24.19.0' + Dependency_ArchTitle,
    Dependency_String(
      'https://nodejs.org/dist/v24.19.0/node-v24.19.0-x86.msi',
      'https://nodejs.org/dist/v24.19.0/node-v24.19.0-x64.msi',
      'https://nodejs.org/dist/v24.19.0/node-v24.19.0-arm64.msi'),
    '',
    False, False);
end;

function InitializeSetup(): Boolean;
begin
  Dependency_AddNode;
  Result := True;
end;

